# Generated by Django 6.0.2 on 2026-03-14 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('event_type', models.CharField(choices=[('mariage', 'Mariage'), ('conference', 'Conférence'), ('anniversaire', 'Anniversaire'), ('soiree', 'Soirée'), ('concert', 'Concert'), ('autre', 'Autre')], max_length=15, verbose_name='Type')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name='Date et heure de début')),
                ('end_date', models.DateTimeField(verbose_name='Date et heure de fin')),
                ('location_address', models.CharField(blank=True, default='', max_length=500, verbose_name='Adresse')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_online', models.BooleanField(default=False, verbose_name='Événement en ligne')),
                ('online_link', models.URLField(blank=True, max_length=512, null=True, verbose_name='Lien de la réunion')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Privé'), ('draft', 'Brouillon')], default='draft', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('live', 'En cours'), ('ended', 'Terminé'), ('souvenir', 'Espace souvenir'), ('archived', 'Archivé')], default='draft', max_length=10)),
                ('template_config', models.JSONField(blank=True, null=True, verbose_name='Configuration JSONB du mini-site')),
                ('palette', models.JSONField(blank=True, null=True, verbose_name='Palette de couleurs (générée par OpenCV)')),
                ('ambiance', models.CharField(blank=True, choices=[('elegant', 'Élégant'), ('festif', 'Festif'), ('minimaliste', 'Minimaliste'), ('colore', 'Coloré'), ('professionnel', 'Professionnel')], default='', max_length=15)),
                ('subdomain', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Sous-domaine (ex: mon-mariage.easevent.app)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date suppression')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='users.domain', verbose_name='Domaine personnalisé (Plan Pro)')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Organisateur')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permissions', models.JSONField(default=dict, help_text='{"can_read": true, "can_add_media": false, "can_edit_components": false, "can_manage_guests": false}', verbose_name='Droits accordés')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'invitation")),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to=settings.AUTH_USER_MODEL, verbose_name='Collaborateur')),
            ],
            options={
                'db_table': 'event_collaborators',
            },
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('r2_key', models.CharField(max_length=512, verbose_name='Clé Cloudflare R2')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], default='photo', max_length=10)),
                ('processing_status', models.CharField(choices=[('pending', 'En attente de traitement'), ('processing', 'Traitement en cours'), ('done', 'Traitement terminé'), ('failed', 'Échec du traitement')], default='pending', max_length=15)),
                ('original_url', models.URLField(blank=True, max_length=512, null=True, verbose_name='URL originale')),
                ('processed_url', models.URLField(blank=True, max_length=512, null=True, verbose_name='URL après traitement')),
                ('dominant_colors', models.JSONField(blank=True, null=True, verbose_name='5 couleurs dominantes (RGB)')),
                ('is_approved', models.BooleanField(default=True, verbose_name="Approuvée par l'organisateur")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='events.event')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='Personne qui a uploadé')),
            ],
            options={
                'db_table': 'event_media',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_hash', models.CharField(max_length=64, unique=True, verbose_name='Empreinte SHA-256')),
                ('config_json', models.JSONField(verbose_name='Configuration JSON du template')),
                ('was_selected', models.BooleanField(default=False, verbose_name="Sélectionné par l'organisateur")),
                ('ml_score', models.FloatField(blank=True, null=True, verbose_name='Score ML de pertinence (0.0 à 1.0)')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_generations', to='events.event')),
            ],
            options={
                'db_table': 'template_generations',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer', 'status'], name='events_organiz_6a581a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['visibility', 'status'], name='events_visibil_408f17_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date'], name='events_start_d_6c01fc_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['subdomain'], name='events_subdoma_504e40_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['latitude', 'longitude'], name='events_latitud_464928_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventcollaborator',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='templategeneration',
            index=models.Index(fields=['config_hash'], name='template_ge_config__a2d0bd_idx'),
        ),
    ]
