# Generated by Django 6.0.2 on 2026-04-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name="Image de couverture de l'événement"),
        ),
    ]
