# Generated by Django 6.0.2 on 2026-03-14 06:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('free', 'Gratuit'), ('standard', 'Standard (9,99€/mois)'), ('pro', 'Pro (24,99€/mois)')], default='free', max_length=10)),
                ('status', models.CharField(choices=[('inactive', 'Inactif'), ('active', 'Actif'), ('paused', 'En pause'), ('past_due', 'Paiement en retard'), ('canceled', 'Annulé')], default='inactive', max_length=10)),
                ('stripe_sub_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='ID abonnement Stripe')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='Début de la période')),
                ('current_period_end', models.DateTimeField(blank=True, help_text="L'accès reste actif jusqu'à cette date même après annulation", null=True, verbose_name='Fin de la période payée')),
                ('cancel_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation programmée")),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation effective")),
                ('billing_interval', models.CharField(choices=[('monthly', 'Mensuel'), ('annual', 'Annuel')], default='monthly', max_length=10, verbose_name='Fréquence de facturation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur abonné')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_8d58fd_idx'), models.Index(fields=['stripe_sub_id'], name='subscriptio_stripe__816563_idx')],
            },
        ),
    ]
