# Generated by Django 6.0.2 on 2026-03-14 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numéro de téléphone (chiffré AES-256 en production)')),
                ('token', models.CharField(help_text='Généré avec secrets.token_urlsafe(32)', max_length=43, unique=True, verbose_name='Token URL-safe 256 bits')),
                ('status', models.CharField(choices=[('sent', 'Envoyée'), ('opened', 'Ouverte'), ('confirmed', 'Confirmée'), ('declined', 'Déclinée'), ('revoked', 'Révoquée'), ('expired', 'Expirée')], default='sent', max_length=15)),
                ('channel', models.CharField(choices=[('sms', 'SMS (via Twilio)'), ('platform_notification', 'Notification in-app')], max_length=25)),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'ouverture")),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration (J+7 après la fin de l'événement)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.event', verbose_name='Événement concerné')),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Membre invité (si inscrit sur Easevent)')),
            ],
            options={
                'db_table': 'invitations',
            },
        ),
        migrations.CreateModel(
            name='RSVPQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField(verbose_name='Texte de la question')),
                ('question_type', models.CharField(choices=[('text', 'Texte libre'), ('radio', 'Choix unique'), ('checkbox', 'Choix multiple'), ('yes_no', 'Oui / Non')], max_length=10)),
                ('is_required', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('options', models.JSONField(blank=True, null=True, verbose_name='Options disponibles (pour radio et checkbox)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_questions', to='events.event', verbose_name='Événement')),
            ],
            options={
                'db_table': 'rsvp_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RSVPResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField(verbose_name="Réponse de l'invité")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_responses', to='invitations.invitation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='invitations.rsvpquestion')),
            ],
            options={
                'db_table': 'rsvp_responses',
            },
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['token'], name='invitations_token_5b330c_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['event', 'status'], name='invitations_event_i_b4995b_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['invited_user', 'status'], name='invitations_invited_0afef7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rsvpresponse',
            unique_together={('question', 'invitation')},
        ),
    ]
