# Generated by Django 6.0.2 on 2026-03-14 06:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name="Date de l'agrégat")),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Vues du mini-site')),
                ('confirmation_count', models.PositiveIntegerField(default=0, verbose_name='Confirmations RSVP')),
                ('feedback_count', models.PositiveIntegerField(default=0, verbose_name='Feedbacks reçus')),
                ('satisfaction_score', models.FloatField(blank=True, null=True, verbose_name='Score global de satisfaction (0 à 100)')),
                ('attendance_predicted', models.FloatField(blank=True, null=True, verbose_name='Taux de présence prédit (0.0 à 1.0)')),
                ('attendance_confidence', models.FloatField(blank=True, null=True, verbose_name='Intervalle de confiance à 80%')),
                ('nlp_summary', models.JSONField(blank=True, null=True, verbose_name='Synthèse NLP des feedbacks')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='events.event', verbose_name='Événement')),
            ],
            options={
                'db_table': 'event_analytics',
                'ordering': ['-date'],
                'unique_together': {('event', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='1 à 5 (correspond aux 5 niveaux visuels)', verbose_name='Note')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Commentaire libre (optionnel)')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Si True, author_id est NULL — irréversible à la soumission', verbose_name='Anonyme')),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positif'), ('neutral', 'Neutre'), ('negative', 'Négatif')], max_length=10, null=True, verbose_name='Sentiment analysé par CamemBERT')),
                ('sentiment_score', models.FloatField(blank=True, null=True, verbose_name='Score de confiance NLP (0.0 à 1.0)')),
                ('topics', models.JSONField(blank=True, null=True, verbose_name='Thèmes extraits automatiquement')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Auteur (null si anonyme)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='events.event', verbose_name='Événement évalué')),
            ],
            options={
                'db_table': 'feedbacks',
                'indexes': [models.Index(fields=['event', 'sentiment'], name='feedbacks_event_i_50c869_idx'), models.Index(fields=['event', 'rating'], name='feedbacks_event_i_c4953f_idx')],
            },
        ),
    ]
