# Generated by Django 6.0.2 on 2026-03-14 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant UUID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Adresse email')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('avatar_url', models.URLField(blank=True, max_length=512, null=True, verbose_name='URL photo de profil (Cloudflare R2)')),
                ('bio', models.CharField(blank=True, default='', max_length=250, verbose_name='Biographie publique')),
                ('is_verified', models.BooleanField(default=False, help_text='Passe à True après clic sur le lien de confirmation', verbose_name='Email vérifié')),
                ('subscription_plan', models.CharField(choices=[('free', 'Gratuit'), ('standard', 'Standard'), ('pro', 'Pro')], default='free', max_length=10, verbose_name="Plan d'abonnement")),
                ('stripe_customer_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='ID client Stripe')),
                ('oauth_provider', models.CharField(blank=True, choices=[('google', 'Google'), ('apple', 'Apple')], max_length=10, null=True, verbose_name='Fournisseur OAuth')),
                ('oauth_uid', models.CharField(blank=True, max_length=128, null=True, verbose_name='Identifiant retourné par Google/Apple')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression (soft delete)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=253, unique=True, verbose_name='Nom de domaine (ex: mes-events.com)')),
                ('status', models.CharField(choices=[('pending', "En attente d'achat"), ('active', 'Actif'), ('expired', 'Expiré'), ('failed', "Échec d'achat")], default='pending', max_length=10)),
                ('namecheap_order_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='ID de commande Namecheap')),
                ('purchased_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'achat")),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Domaine personnalisé',
                'db_table': 'domains',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notif_invitation', models.BooleanField(default=True, verbose_name='Invitation reçue')),
                ('notif_confirmation', models.BooleanField(default=True, verbose_name="Quelqu'un confirme mon événement")),
                ('notif_event_modified', models.BooleanField(default=True, verbose_name='Un événement modifié')),
                ('notif_comment', models.BooleanField(default=True, verbose_name='Nouveau commentaire')),
                ('notif_message', models.BooleanField(default=True, verbose_name='Nouveau message direct')),
                ('notif_reminder', models.BooleanField(default=True, verbose_name='Rappels J-7 / J-1 / Jour J')),
                ('notif_feedback_req', models.BooleanField(default=True, verbose_name='Demande de feedback')),
                ('notif_daily_report', models.BooleanField(default=True, verbose_name='Bilan quotidien à 20h')),
                ('notif_final_report', models.BooleanField(default=True, verbose_name='Rapport final disponible')),
                ('notif_payment', models.BooleanField(default=True, verbose_name='Paiement confirmé/échoué')),
                ('geolocation_enabled', models.BooleanField(default=False, verbose_name="Géolocalisation activée pour le fil d'actualité")),
                ('language', models.CharField(default='fr', max_length=5, verbose_name="Langue de l'interface (code ISO)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférences utilisateur',
                'db_table': 'user_preferences',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['subscription_plan'], name='users_subscri_95bd21_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['deleted_at'], name='users_deleted_e48316_idx'),
        ),
    ]
